name: Deploy on Github

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.4]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install 
    - name: Build Page
      run: yarn start
      env:
        META_TITLE: ${{ secrets.META_TITLE }}
        META_DESCRIPTION: ${{ secrets.META_DESCRIPTION }}
        META_AUTHOR: ${{ secrets.META_AUTHOR }}
        THEME: ${{ secrets.THEME }}
        FAVICON_URL: ${{ secrets.FAVICON_URL }}
        AVATAR_URL: ${{ secrets.AVATAR_URL }}
        AVATAR_ALT: ${{ secrets.AVATAR_ALT }}
        AVATAR_2X_URL: ${{ secrets.AVATAR_2X_URL }}
        NAME: ${{ secrets.NAME }}
        BIO: ${{ secrets.BIO }}
        CAL_URL: ${{ secrets.CAL_URL }}
        GITHUB: ${{ secrets.GITHUB }}
        TWITTER: ${{ secrets.TWITTER }}
        MASTODON: ${{ secrets.MASTODON }}
        MICRO_BLOG: ${{ secrets.MICRO_BLOG }}
        INSTAGRAM: ${{ secrets.INSTAGRAM }}
        FACEBOOK: ${{ secrets.FACEBOOK }}
        FACEBOOK_MESSENGER: ${{ secrets.FACEBOOK_MESSENGER }}
        LINKED_IN: ${{ secrets.LINKED_IN }}
        YOUTUBE: ${{ secrets.YOUTUBE }}
        DISCORD: ${{ secrets.DISCORD }}
        TWITCH: ${{ secrets.TWITCH }}
        PRODUCT_HUNT: ${{ secrets.PRODUCT_HUNT }}
        SNAPCHAT: ${{ secrets.SNAPCHAT }}
        SPOTIFY: ${{ secrets.SPOTIFY }}
        REDDIT: ${{ secrets.REDDIT }}
        MEDIUM: ${{ secrets.MEDIUM }}
        PINTEREST: ${{ secrets.PINTEREST }}
        TIKTOK: ${{ secrets.TIKTOK }}
        EMAIL: ${{ secrets.EMAIL }}
        EMAIL_TEXT: ${{ secrets.EMAIL_TEXT }}
        EMAIL_ALT: ${{ secrets.EMAIL_ALT }}
        EMAIL_ALT_TEXT: ${{ secrets.EMAIL_ALT_TEXT }}
        SOUND_CLOUD: ${{ secrets.SOUND_CLOUD }}
        FIGMA: ${{ secrets.FIGMA }}
        KIT: ${{ secrets.KIT }}
        TELEGRAM: ${{ secrets.TELEGRAM }}
        TUMBLR: ${{ secrets.TUMBLR }}
        STEAM: ${{ secrets.STEAM }}
        VIMEO: ${{ secrets.VIMEO }}
        WORDPRESS: ${{ secrets.WORDPRESS }}
        GOODREADS: ${{ secrets.GOODREADS }}
        SKOOB: ${{ secrets.SKOOB }}
        LETTERBOXD: ${{ secrets.LETTERBOXD }}
        FOOTER: ${{ secrets.FOOTER }}
    - name: Commit changes
      uses: EndBug/add-and-commit@v5
      with:
        author_name: Shubham Kumar
        author_email: hello@shubhkumar.in
        message: "Commit Updates"
        add: "*"
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
